### ISSUE TITLE
Bug when /usr/bin/python is Python 3

### ISSUE THREAD

**Issue by Asher256** [swade1987/hands-on-with-kubernetes-workshop#5]
The command:
```
 make provision-cluster 
```

Gave me the error:
```
2017-02-09 01:01:32.398+0000 - export PYTHONPATH=/home/workshop/hands-on-with-kubernetes-workshop/ansible/lib/python2.7/site-packages:/home/workshop/hands-on-with-kubernetes-workshop/ansible/lib64/python2.7/site-packages
2017-02-09 01:01:32.398+0000 - export ANSIBLE_CALLBACK_PLUGINS=ansible/playbooks/callback
2017-02-09 01:01:32.398+0000 - export ANSIBLE_CALLBACK_WHITELIST=json_lines
2017-02-09 01:01:32.398+0000 - export ANSIBLE_CONFIG=ansible/playbooks/ansible.cfg
2017-02-09 01:01:32.398+0000 - export ANSIBLE_JSON_LINES_PIPE=/tmp/ansible-pipe-2296349169875352194-2017-02-08-20-01-32.39856
2017-02-09 01:01:32.398+0000 - ansible/bin/ansible-playbook -i ansible/inventory.ini -s ansible/playbooks/preflight.yaml --extra-vars @ansible/clustercatalog.yaml -vvvv
2017-02-09 01:01:32.429+0000 - Traceback (most recent call last):
2017-02-09 01:01:32.429+0000 -   File "ansible/bin/ansible-playbook", line 36, in <module>
2017-02-09 01:01:32.429+0000 -     import shutil
2017-02-09 01:01:32.429+0000 -   File "/usr/lib/python3.6/shutil.py", line 10, in <module>
2017-02-09 01:01:32.429+0000 -     import fnmatch
2017-02-09 01:01:32.429+0000 -   File "/usr/lib/python3.6/fnmatch.py", line 14, in <module>
2017-02-09 01:01:32.429+0000 -     import re
2017-02-09 01:01:32.429+0000 -   File "/usr/lib/python3.6/re.py", line 142, in <module>
2017-02-09 01:01:32.429+0000 -     class RegexFlag(enum.IntFlag):
2017-02-09 01:01:32.429+0000 - AttributeError: module 'enum' has no attribute 'IntFlag'
```

The bug below happened because /usr/bin/python was pointing to Python 3 in my operating system (Arch Linux).  

To solve the issue I had to change the shebang of all scripts ./hands-on-with-kubernetes-workshop/ansible/bin/ansible* from "#!/usr/bin/env python" to "#!/usr/bin/env python2".

Recommendation: it would have been better if it was possible to use the Ansible version installed by the operating system, locate in the $PATH /usr/bin/ansible .

**Comment by Asher256** [comment]
Yes

**Comment by swade1987** [comment]
Perfect, I have re-structured the workshop now so this won't happen again. Interesting issue though that I passed onto our product team.
